services:
    frontend:
        image: pms-frontend:1698174535
        container_name: pms-frontend
        environment:
          - VUE_APP_API_URL=https://api.tyrantrex.icu
        ports:
          - 8001:80
        restart: unless-stopped
        depends_on:
          backend:
            condition: service_started

    backend:
        image: pms-backend:1698169544
        container_name: pms-backend
        environment:
            # optional
            # - DATABASE="PMS"
            # mysql ip address
            - HOST=172.30.0.2
            - USER=root
            # should be same as mysql.MYSQL_ROOT_PASSWORD
            - PASSWORD=Abc!@#$%^&*()
            - JWT_SECRET=Xyz)(*&^%$#@!)
        ports:
          - 8000:8080
        restart: unless-stopped
        depends_on:
          mysql:
            condition: service_started

    mysql:
        image: mysql:latest
        environment:
            # should be same as pms.PASSWORD
            - MYSQL_ROOT_PASSWORD=Abc!@#$%^&*()
        ports:
          - 3306:3306
        restart: unless-stopped